package helper_test

import (
	"category/helper"
	"math/rand"
	"net/url"
	"sort"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/oklog/ulid"
)

func TestNew(t *testing.T) {

	prefix := "cat"
	testNew(t, helper.New(prefix), prefix)
}

func TestULID(t *testing.T) {
	id := helper.New("cat")
	if _, err := ulid.Parse(id[len("cat_"):]); err != nil {
		t.Errorf("func New not generating ulids: %v", err)
	}
}

func TestURLSafe(t *testing.T) {
	for range [20]struct{}{} {
		id := helper.New("cat")

		if url.PathEscape(id) != id {
			t.Errorf("value generated by New is not url path safe, expected: %s, got: %s", url.PathEscape(id), id)
		}

		if url.QueryEscape(id) != id {
			t.Errorf("value generated by New is not url query safe, expected: %s, got: %s", url.QueryEscape(id), id)
		}
	}
}

func TestUniqueness(t *testing.T) {
	set := map[string]bool{}
	for range [10000]struct{}{} {
		id := helper.New("cat")
		if set[id] {
			t.Errorf("generating repeated strings")
		}

		set[id] = true
	}
}

func TestUniquenessParallel(t *testing.T) {
	var wg sync.WaitGroup

	ids := make(chan string, 1000)
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func(ids chan<- string) {
			defer wg.Done()

			for i := 0; i < 100; i++ {
				ids <- helper.New("usr")
			}
		}(ids)
	}

	go func() {
		wg.Wait()
		close(ids)
	}()

	set := map[string]bool{}
	for id := range ids {
		if set[id] {
			t.Errorf("generating repeated strings")
		}

		set[id] = true
	}
}

func TestLexicalOrder(t *testing.T) {
	var ii [1000]string
	for k := range ii {
		ii[k] = helper.New("cat")
	}

	if !sort.StringsAreSorted(ii[:]) {
		t.Errorf("should generate lexically sorted ids")
		for _, v := range ii {
			t.Log(v)
		}
	}
}

func TestGenerator_New(t *testing.T) {
	const prefix = "cat"
	pg := helper.Generator{
		Prefix: prefix,
	}
	testNew(t, pg.New(), prefix)
}

func TestPrefix(t *testing.T) {
	tests := []struct {
		name string
		id   string
		want string
	}{
		{
			name: "Empty",
			id:   "",
			want: "",
		},
		{
			name: "Good",
			id:   helper.New("cat"),
			want: "cat",
		},
		{
			name: "ulid",
			id:   helper.New("c")[2:],
			want: "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := helper.Prefix(tt.id); got != tt.want {
				t.Errorf("Prefix() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestTime(t *testing.T) {
	tests := []struct {
		name    string
		id      string
		want    uint64
		wantErr error
	}{
		{
			name:    "Empty",
			id:      "",
			want:    0,
			wantErr: helper.ErrMalformed,
		},
		{
			name:    "Valid",
			id:      "cat_" + ulid.MustNew(ulid.MaxTime(), rand.New(rand.NewSource(time.Now().UnixNano()))).String(),
			want:    ulid.MaxTime(),
			wantErr: nil,
		},
		{
			name:    "Valid Without Prefix",
			id:      ulid.MustNew(ulid.MaxTime(), rand.New(rand.NewSource(time.Now().UnixNano()))).String(),
			want:    ulid.MaxTime(),
			wantErr: nil,
		},
		{
			name:    "Malformed",
			id:      "cat_" + uuid.Must(uuid.NewUUID()).String(),
			wantErr: helper.ErrMalformed,
			want:    0,
		},
		{
			name:    "Just Prefix",
			id:      "cat_",
			wantErr: helper.ErrMalformed,
			want:    0,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := helper.Time(tt.id)
			if err != tt.wantErr {
				t.Errorf("Time() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("Time() = %v, want %v", got, tt.want)
			}
		})
	}
}

func testNew(t *testing.T, id, prefix string) {
	t.Helper()
	if !strings.HasPrefix(id, prefix+"_") {
		t.Errorf("New should return a ulid with the given prefix, expected: cat, got: %s", id)
	}
}

func BenchmarkNew(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = helper.New("cat")
	}
}

func BenchmarkNewParallel(b *testing.B) {
	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			_ = helper.New("cat")
		}
	})
}
